### ISSUE TITLE
Re-examine Location class and degree/radian conversions

### ISSUE THREAD

**Issue by kevinmilner** [opensha/opensha#25] opened 2021-06-11 21:49 UTC
Our [Location class](https://github.com/opensha/opensha/blob/master/src/main/java/org/opensha/commons/geo/Location.java) stores values internally in radians. I think this was done by @pmpowers-usgs in order to speed up location calculations. I noticed some strange behavior, however, where the following fails due to rounding errors:

```
double lat = 37.09084333164281;
Preconditions.checkState(lat == new Location(lat, 0d).getLatitude());
```

This fails because the latitude gets converted to radians, then getLatitude() returns a version converted back from radians, and that returned value is `37.090843331642816` (notice the extra digit, a `6` at the end).

Internally, the input latitude of `37.09084333164281` becomes `0.6473573384785501`, but when that is converted back to degrees it becomes `37.090843331642816`, which in turn will convert back to radians as `0.6473573384785503`.

There are multiple ways to convert between radians and degrees, and Java actually switched their method in JDK 9+ [thanks to this report](https://bugs.openjdk.java.net/browse/JDK-8051808).

Here's how our particular number is affected by the various algorithms:

```
INPUT DEG	37.09084333164281
Using Java 9+ Math.toRadians/toDegrees:
	RAD:	0.6473573384785501
	DEG:	37.090843331642816
Using Pre-Java 9: /180*PI and *180/PI
	RAD:	0.64735733847855
	DEG:	37.09084333164281
Using BigDecimal
	RAD:	0.6473573384785501
	DEG:	37.09084333164281
```

So the difference for this value is due to the change in Java 9+. But I believe them that the change was for the better, and is more accurate more of the time. I tried their sample code and found that, for 1000 trials, the Java 9 method wins 2420 of the time, Pre-Java 9 wins 336 times, and the rest are ties. So this particular latitude is probably one of those rare cases where the old code worked better.

I see a few options:

1. Go back to storing things in degrees, as that's how they're almost always created/serialized
  a. PROS: Serialization will always work, equals() will always work as expected
  b. CONS: LocationUtils calculations will be slightly slower, but I'm not sure by how much
2. Store both degrees and radians
  a. PROS: Serialization will always work, equals() will always work as expected, calculations will still be as fast
  b. CONS: Memory requirements of Location class increase (must store 2 more double values), and this is a core class that can exist many thousands of times in memory
3. Switch to BigDecimal for accurate conversion, still just store in radians
  a. PROS: Serialization will always work, equals() will always work as expected, calculations will still be as fast
  b. CONS: Initialization of Location objects will be slower, as will getLatitude() and getLongitude() methods
4. Do nothing
  a. PROS: No work, lowest memory footprint and calculations are still fast
  b. CONS: Equals and serialization don't work as expected

**Comment by kevinmilner** [comment] 2021-06-11 21:51
As an example of how de-serialization can impact things, here's how I discovered the issue:

If you generate a fault system rupture set in memory for the default UCERF3 logic tree branch:

```
LogicTreeBranch origBranch = LogicTreeBranch.DEFAULT;
InversionFaultSystemRupSet rupSet = InversionFaultSystemRupSetFactory.forBranch(origBranch);
```

The InversionTargetMFDs debug info will be:

```
	totalRegionRateMgt5 =	7.9
	mMaxOffFault =	7.55
	applyImpliedCouplingCoeff =	false
	spatialSeisPDF =	UCERF3
	spatialSeisPDFforOnFaultRates =	UCERF3
	inversionModel =	Characteristic (Constrained)
	fractSeisInSoCal =	0.5255737
	fractionSeisOnFault =	0.5782895
	onFaultRegionRateMgt5 =	4.568487
	offFaultRegionRateMgt5 =	3.3315127
	origOnFltDefModMoRate =	1.8792723E19
	offFltDefModMoRate =	8.753289E18
	roundedMmaxOnFault =	8.25
	totalTargetGR(5.05) =	7.8960404
	aveMinSeismoMag =	6.25
	impliedOnFaultCouplingCoeff =	1.1901385
	finalOffFaultCouplingCoeff =	0.31081182
	impliedTotalCouplingCoeff =	0.9105143
	trulyOffFaultMFD(5.05) =	3.3162255
	totalSubSeismoOnFaultMFD(5.05) =	4.161011
	targetOnFaultSupraSeisMFD(5.05) =	0.4448955
	sum of above three =	7.922132
	noCalTargetMFD(5.05) =	0.21107012
	soCalTargetMFD(5.05) =	0.23382537
	sum of above two =	0.4448955
```

Then then save that IVFSRS to a file, and load it back:

```
FaultSystemIO.writeRupSet(rupSet, tempFile);
rupSet = FaultSystemIO.loadInvRupSet(tempFile);
```

And some of those values change, they are now:

```
	totalRegionRateMgt5 =	7.9
	mMaxOffFault =	7.55
	applyImpliedCouplingCoeff =	false
	spatialSeisPDF =	UCERF3
	spatialSeisPDFforOnFaultRates =	UCERF3
	inversionModel =	Characteristic (Constrained)
	fractSeisInSoCal =	0.5255737
	fractionSeisOnFault =	0.57828945
	onFaultRegionRateMgt5 =	4.5684867
	offFaultRegionRateMgt5 =	3.3315134
	origOnFltDefModMoRate =	1.8792723E19
	offFltDefModMoRate =	8.753289E18
	roundedMmaxOnFault =	8.25
	totalTargetGR(5.05) =	7.8960404
	aveMinSeismoMag =	6.25
	impliedOnFaultCouplingCoeff =	1.1901385
	finalOffFaultCouplingCoeff =	0.31081185
	impliedTotalCouplingCoeff =	0.9105143
	trulyOffFaultMFD(5.05) =	3.316226
	totalSubSeismoOnFaultMFD(5.05) =	4.1610103
	targetOnFaultSupraSeisMFD(5.05) =	0.44489557
	sum of above three =	7.922132
	noCalTargetMFD(5.05) =	0.21107015
	soCalTargetMFD(5.05) =	0.23382542
	sum of above two =	0.44489557
```

The differences are more easily seen as a diff:

```diff
9,11c9,11
< 	fractionSeisOnFault =	0.5782895
< 	onFaultRegionRateMgt5 =	4.568487
< 	offFaultRegionRateMgt5 =	3.3315127
---
> 	fractionSeisOnFault =	0.57828945
> 	onFaultRegionRateMgt5 =	4.5684867
> 	offFaultRegionRateMgt5 =	3.3315134
18c18
< 	finalOffFaultCouplingCoeff =	0.31081182
---
> 	finalOffFaultCouplingCoeff =	0.31081185
20,22c20,22
< 	trulyOffFaultMFD(5.05) =	3.3162255
< 	totalSubSeismoOnFaultMFD(5.05) =	4.161011
< 	targetOnFaultSupraSeisMFD(5.05) =	0.4448955
---
> 	trulyOffFaultMFD(5.05) =	3.316226
> 	totalSubSeismoOnFaultMFD(5.05) =	4.1610103
> 	targetOnFaultSupraSeisMFD(5.05) =	0.44489557
24,26c24,26
< 	noCalTargetMFD(5.05) =	0.21107012
< 	soCalTargetMFD(5.05) =	0.23382537
< 	sum of above two =	0.4448955
---
> 	noCalTargetMFD(5.05) =	0.21107015
> 	soCalTargetMFD(5.05) =	0.23382542
> 	sum of above two =	0.44489557
```

These are minor differences, but they do slightly change inversion constraints, enough-so that inversion inputs generated with the original in-memory and loaded rupture sets will not be equal even to 4-byte floating point precision.

**Comment by pmpowers-usgs** [comment] 2021-06-14 14:47
The NSHM codes now store the original lat lon in decimal degrees to guarantee serialization to the original intended values and expose package private radians fields for internal use.

**Comment by mbarall** [comment] 2021-06-16 20:49
Options 1 and 2 both seem feasible.  Option 3 won't fix the problem, because there will always be angles where conversion from degrees to radians and back to degrees does not yield the original value.  The issue isn't the accuracy of the conversion, it's that the binary representation of floating-point numbers does not allow one-to-one correspondence between degree values and radian values.  Also, conversion via BigDecimal would be very slow.

For what it's worth, the OAF code internally stores angles as decimal degrees and converts to radians whenever needed, like option 1.

**Comment by kevinmilner** [comment] 2021-06-17 19:26
Looking into memory usage a bit (and confirming with some crude tests), our current Location class uses 40 bytes per instance and a version that stored values both in degrees and radians would use 56 bytes.

For option 2 (storing both degrees and radians), that's a 40% increase in memory usage. For 1 million location instances, which is slightly more than are created when instantiating branch-averaged MeanUCERF3 and computing a hazard curve including background seismicity, that's an increase in ~15 MB (not much). UCERF2 instantiates many more locations, however: 35 million instances which would mean another ~500 MB of memory if all are kept in memory at the same time, but most are temporary so that's not an issue (you can compute U2 hazard curves with less than 500 MB of total memory, and VisualVM suggests that fewer than 2 million are actually in memory at once).

For option 1, I tested distance calculations where I overrode the get[Lat/Lon]Rad() methods to do the conversion on the fly. I found a 32% increase in time-to-solution with this method.

I think I'm going to go with option 2 (storing both), as memory usage from this class is relatively low in normal calculations and we often do many calculations for a single location, and I'd rather not slow down hazard calculations by 30% across the board.

**Closed** 2021-06-25 16:09 UTC
